apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  # Specify the size of the storage
  storageClassName: expense-ebs  # Referencing the StorageClass created above


