
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim  # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce  # The volume can only be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi  # Request 5Gi of storage
  storageClassName: expense-ebs  # Reference to the StorageClass 'expense-ebs'
