apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Access mode: RWO (ReadWriteOnce), ROX (ReadOnlyMany), RWX (ReadWriteMany)
  resources:
    requests:
      storage: 5Gi  # Amount of storage requested
  storageClassName: standard  # Name of the StorageClass that will handle provisioning
