apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim  # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce  # The volume can be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi  # Requested storage size (e.g., 10Gi)
  storageClassName: ebs-sc  # Use the StorageClass created earlier


apiVersion: v1
kind: Pod
metadata:
  name: my-pod  # Name of the Pod
spec:
  nodeSelector:
    failure-domain.beta.kubernetes.io/zone: us-east-1a  # Ensure Pod is scheduled in us-east-1a
  containers:
    - name: nginx  # Name of the container
      image: nginx:latest  # Image to run in the container
      volumeMounts:
        - mountPath: /usr/share/nginx/html  # Path inside the container to mount the volume
          name: ebs-storage  # Volume name
  volumes:
    - name: ebs-storage  # Name of the volume referenced in the container
      persistentVolumeClaim:
        claimName: my-claim  # PVC to use for this volume

