
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim  # Name of the PVC
spec:
  accessModes:
    - ReadWriteOnce  # The volume can only be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi  # Request 5Gi of storage
  storageClassName: expense-ebs  # Reference to the StorageClass 'expense-ebs'
---  

apiVersion: v1
kind: Pod
metadata:
  name: my-pod  # Name of the Pod
  labels:
    name: nginx
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1a  # Ensure Pod is scheduled in the correct zone (e.g., us-east-1a)
  containers:
    - name: nginx  # Container running nginx
      image: nginx:latest  # Use the latest nginx image
      volumeMounts:
        - mountPath: /usr/share/nginx/html  # Path inside the container to mount the volume
          name: ebs-storage  # Reference to the volume by name
  volumes:
    - name: ebs-storage  # Name of the volume referenced in the container
      persistentVolumeClaim:
        claimName: my-claim  # The PVC to be used by this Pod
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service  # Name of the Service
spec:
  selector:
    name: nginx  # Select Pods with the 'name: nginx' label
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 80  # Port the container is listening on
  type: LoadBalancer  # Exp