apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-07253c9f95a2fe485


    apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-storage-pv
spec:
  capacity:
    storage: 5Gi  # 5 GB of storage
  accessModes:
    - ReadWriteOnce  # The volume can be mounted by only one pod at a time and can be read/written by that pod.
  hostPath:
    path: /mnt/data/nginx  # Using a local disk for storage (you could use cloud storage like EBS)
  persistentVolumeReclaimPolicy: Retain  # Don't delete the volume after the pod is deleted (retain the data)
