apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2  # EBS volume type
  fsType: ext4  # File system type
reclaimPolicy: Retain  # Options: Delete, Retain, Recycle
volumeBindingMode: WaitForFirstConsumer  # Wait for a pod to request a volume before binding it
