apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80           # Service port
      targetPort: 80     # Container port
      nodePort: 30007    # Optional NodePort; Kubernetes can choose if omitted
