apiVersion: apps/v1
kind: ReplicaSet
metadata: 
 name: replica
 labels:
  name: ari
spec:
  replicas: 3
  selector:
    matchLabels:
      name: ari
  template:
    metadata:
      labels:
        name: ari
    spec:
     containers:
      - name: nginx
        image: nginx
        ports:
         containerPort: 80

