apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
  labels:
    name: replica
spec:
  replicas: 3  # Corrected to lowercase
  selector:
    matchLabels:
      name: replica
  template:
    metadata:
      labels:
        name: replica  # The name field here is not strictly necessary
    spec:
      containers:
      - name: nginx-container  # Added container name
        image: nginx
        ports:
        - containerPort: 80
