apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: replica
 labels:
   name: naveen
spec:
 replicas: 2
 selector:
  matchLabels: 
    name: naveen
 template:
  metadata:
    name: pod
    labels:
      name: naveen

  spec: 
    containers:
      image: nginx
      ports:
      - containerPort: 80      
    


   
 
