apiVersion: apps/v1
kind: Deployment
metadata:
 name: deploy
 labels: 
   name: hi
spec:
   replicas: 2
   selector:
     matchLabels: 
       name: hi
   template:
     metadata:
       labels:
         name: hi
     spec:
       containers:
        - name: nginx
          image: nginx          


---
apiVersion: v1
kind: Service
metadata:
  name: service1
  labels:
   name: hi
spec:
  ports:
   - port: 80
     targetPort: 80   