apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  labels:
    name: deploy
spec:
  replicas: 3  # Corrected to lowercase
  selector:
    matchLabels:
      name: deploy
  template:
    metadata:
      labels:
        name: deploy  # The name field here is not strictly necessary
    spec:
      containers:
      - name: nginx-container  # Added container name
        image: nginx
        ports:
        - containerPort: 80

        
