apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    name: hi

spec:
  selector:
    matchLabels:
     name: hi
  template:
   metadata:
    labels:
      name: hi
   spec:
    containers:
     name: nginx
     image: nginx

