apiVersion: apps/v1
kind: Deployment
metadata:
  name: hi
  labels:
    name: hi

spec:
  replicas: 3 
  selector:
    matchLabels:
     name: hi
  template:
   metadata:
    labels:
      name: hi
   spec:
    containers:
      - name: nginx
        image: nginx  

---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    name: hi
spec:
 selector:
   name: hi
 ports:
  - port: 80
    targetPort: 80
    protocol: TCP                
