apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
   name: expense
   environment: dev
spec:
  containers:
    - name: nginx
      image: nginx
      env:
       - name: course
         value: devops     