apiVersion: v1
kind: Pod
metadata:
  name: expense
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: nginx1
      image: nginx
      ports:
        - containerPort: 81 # Different port for the second container
