apiVersion: v1
kind: Pod
metadata:
  name: expense
spec:
  containers:
    - name: nginx
      image: nginx
      
    - name: nginx1
      image: nginx
        # Different port for the second container
