apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: nginx
      image: nginx 


apiVersion: v1
kind: hi
metadata:
  name: pod
spec:
  containers:
    - name: nginx3
      image: nginx       


    