apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
    - name: nginx
      image: nginx 

apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
    - name: nginx1
      image: nginx 

    