apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello
spec:
  replicas: 2
  selector:
   matchLabels:
     name: hello
  template:
   metadata:
     label:
       name: hello
   spec:
     containers:
       - name: nginx
         image: nginx
         
