apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: hello
spec:
  replicas: 2
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels: 
        name: hello
    spec:
      containers:
        - name: nginx
          image: nginx

---
  apiVersion: v1
  kind: Service
  metadata:
    name: service-1
  spec:  
   selector:
    labels:
      name: hello
   ports:
    - port: 80
      ContainerPort: 80
      protocol: TCP
         


        