apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: hello
spec:
  repliccas: 2
  selector:
    matchLabels:
      name: hello
  template:
    metadata:
      labels: 
        name: hello
    spec:
      containers:
        - name: nginx
          image: nginx

        