apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello1
spec:
  replicas: 2
  selector:
   matchLabels:
     name: hello
  template:
   metadata:
     labels:
       name: hello
   spec:
     containers:
       - name: nginx
         image: nginx

---
apiVersion: v1
kind: Service
metadata:
 name: service
spec:
  selector:
    name: hello
  ports:
   - port: 80
     targetPort: 80
     protocol: TCP
  type: LoadBalancer      



