apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: expense
  name: backend
  labels:
    app: backend
    project: expense

spec:
  replicas: 3 
  selector:
    matchLabels:
     app: backend
     project: expense
  template:
   metadata:
    labels:
      app: backend
      project: expense
   spec:
    containers:
      - name: backend
        image: joindevops/backend:v1

---
apiVersion: v1
kind: Service
metadata:
  
  labels:
    name: hello
    
spec:
 selector:
   app: backend
   project: expense

 ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP  
                 
