apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense  # Optional: specify your namespace here
  labels:
    app: backend
    env: dev
spec:
  replicas: 2  # Number of desired pods
  selector:
    matchLabels:
      app: backend
      env: dev
      
  template:
    metadata:
      labels:
        app: backend
        env: dev
    spec:
      containers:
      - name: backend
        image: joindevops/backend:v1  # Specify the Docker image
        envFrom:
        - configMapRef:
            name: backend
        
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense # Optional: specify your namespace here
spec:
  type: ClusterIP  # Change to NodePort or LoadBalancer if needed
  selector:
     app: backend
     env: dev
  ports:
    - port: 8080  # Port exposed by the service
      targetPort: 8080 # Port on the pod to forward traffic to
      protocol: TCP